baseURL = "https://jesusguarneros.github.io/my_launchx_blog/"
languageCode = "en-us"
title = "Bit√°cora de Viaje de Jes√πs Santiago Guarneros"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aqu√≠ pon tu twitter üëá
  twitter_handle = "@Jes√πsGuarneros7"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
